### ISSUE TITLE
Improving scope handling of std::unique_lock to avoid premature unlock

### ISSUE THREAD

**Issue by pqviet07** [thanhit95/multi-threading#2]
_Line 40:_ `uniquelk(mut);`  https://github.com/thanhit95/multi-threading/blob/main/cpp/cpp-std/demo17c-reentrant-lock.cpp

I've encountered a potential issue in the synchronization logic involving `std::recursive_mutex` and `std::unique_lock`. The current implementation creates temporary `std::unique_lock` objects that are **not assigned to variables**. This results in the locks being **released immediately after their creation** due to the **temporary objects** going out of scope. I wonder if this approach was chosen for specific reasons that I might not be aware of.

**Comment by thanhit95** [comment]
Thank you for identifying the mistake. I've made the commit 9557cdf to fix it.
